from validacoes_pecas import (
    STATUS_APROVADO,
    STATUS_REPROVADO,
    MOTIVO_REPROVADO_POR_PESO,
    MOTIVO_REPROVADO_POR_COR,
    MOTIVO_REPROVADO_POR_COMPRIMENTO,
)

lista_de_pecas = [
    # ======================
    # 43 APROVADAS
    # ======================
    {
        "id": 1,
        "peso": 100,
        "cor": "AZUL",
        "comprimento": 15,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 2,
        "peso": 100,
        "cor": "VERDE",
        "comprimento": 15,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 3,
        "peso": 98,
        "cor": "AZUL",
        "comprimento": 12,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 4,
        "peso": 102,
        "cor": "VERDE",
        "comprimento": 18,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 5,
        "peso": 95,
        "cor": "AZUL",
        "comprimento": 10,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 6,
        "peso": 105,
        "cor": "VERDE",
        "comprimento": 20,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 7,
        "peso": 99,
        "cor": "AZUL",
        "comprimento": 14,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 8,
        "peso": 101,
        "cor": "VERDE",
        "comprimento": 16,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 9,
        "peso": 100,
        "cor": "AZUL",
        "comprimento": 17,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 10,
        "peso": 97,
        "cor": "VERDE",
        "comprimento": 13,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 11,
        "peso": 103,
        "cor": "AZUL",
        "comprimento": 19,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 12,
        "peso": 96,
        "cor": "VERDE",
        "comprimento": 11,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 13,
        "peso": 100,
        "cor": "AZUL",
        "comprimento": 15,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 14,
        "peso": 104,
        "cor": "VERDE",
        "comprimento": 20,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 15,
        "peso": 95,
        "cor": "AZUL",
        "comprimento": 12,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 16,
        "peso": 105,
        "cor": "VERDE",
        "comprimento": 18,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 17,
        "peso": 98,
        "cor": "AZUL",
        "comprimento": 16,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 18,
        "peso": 101,
        "cor": "VERDE",
        "comprimento": 14,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 19,
        "peso": 100,
        "cor": "AZUL",
        "comprimento": 15,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 20,
        "peso": 99,
        "cor": "VERDE",
        "comprimento": 17,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 21,
        "peso": 102,
        "cor": "AZUL",
        "comprimento": 18,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 22,
        "peso": 97,
        "cor": "VERDE",
        "comprimento": 13,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 23,
        "peso": 100,
        "cor": "AZUL",
        "comprimento": 15,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 24,
        "peso": 103,
        "cor": "VERDE",
        "comprimento": 19,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 25,
        "peso": 96,
        "cor": "AZUL",
        "comprimento": 11,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 26,
        "peso": 104,
        "cor": "VERDE",
        "comprimento": 20,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 27,
        "peso": 98,
        "cor": "AZUL",
        "comprimento": 14,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 28,
        "peso": 101,
        "cor": "VERDE",
        "comprimento": 16,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 29,
        "peso": 100,
        "cor": "AZUL",
        "comprimento": 15,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 30,
        "peso": 97,
        "cor": "VERDE",
        "comprimento": 13,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 31,
        "peso": 102,
        "cor": "AZUL",
        "comprimento": 18,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 32,
        "peso": 99,
        "cor": "VERDE",
        "comprimento": 17,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 33,
        "peso": 100,
        "cor": "AZUL",
        "comprimento": 15,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 34,
        "peso": 103,
        "cor": "VERDE",
        "comprimento": 19,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 35,
        "peso": 96,
        "cor": "AZUL",
        "comprimento": 11,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 36,
        "peso": 104,
        "cor": "VERDE",
        "comprimento": 20,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 37,
        "peso": 98,
        "cor": "AZUL",
        "comprimento": 14,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 38,
        "peso": 101,
        "cor": "VERDE",
        "comprimento": 16,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 39,
        "peso": 100,
        "cor": "AZUL",
        "comprimento": 15,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 40,
        "peso": 97,
        "cor": "VERDE",
        "comprimento": 13,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 41,
        "peso": 102,
        "cor": "AZUL",
        "comprimento": 18,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 42,
        "peso": 99,
        "cor": "VERDE",
        "comprimento": 17,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    {
        "id": 43,
        "peso": 100,
        "cor": "AZUL",
        "comprimento": 15,
        "status": STATUS_APROVADO,
        "motivos_reprovacao": [],
    },
    # ======================
    # 35 REPROVADAS
    # ======================
    # Peso inválido
    {
        "id": 44,
        "peso": 80,
        "cor": "AZUL",
        "comprimento": 15,
        "status": STATUS_REPROVADO,
        "motivos_reprovacao": [MOTIVO_REPROVADO_POR_PESO],
    },
    {
        "id": 45,
        "peso": 80,
        "cor": "VERDE",
        "comprimento": 15,
        "status": STATUS_REPROVADO,
        "motivos_reprovacao": [MOTIVO_REPROVADO_POR_PESO],
    },
    {
        "id": 46,
        "peso": 110,
        "cor": "AZUL",
        "comprimento": 15,
        "status": STATUS_REPROVADO,
        "motivos_reprovacao": [MOTIVO_REPROVADO_POR_PESO],
    },
    {
        "id": 47,
        "peso": 110,
        "cor": "VERDE",
        "comprimento": 15,
        "status": STATUS_REPROVADO,
        "motivos_reprovacao": [MOTIVO_REPROVADO_POR_PESO],
    },
    {
        "id": 48,
        "peso": 70,
        "cor": "AZUL",
        "comprimento": 15,
        "status": STATUS_REPROVADO,
        "motivos_reprovacao": [MOTIVO_REPROVADO_POR_PESO],
    },
    {
        "id": 49,
        "peso": 70,
        "cor": "VERDE",
        "comprimento": 15,
        "status": STATUS_REPROVADO,
        "motivos_reprovacao": [MOTIVO_REPROVADO_POR_PESO],
    },
    {
        "id": 50,
        "peso": 120,
        "cor": "AZUL",
        "comprimento": 15,
        "status": STATUS_REPROVADO,
        "motivos_reprovacao": [MOTIVO_REPROVADO_POR_PESO],
    },
    {
        "id": 51,
        "peso": 120,
        "cor": "VERDE",
        "comprimento": 15,
        "status": STATUS_REPROVADO,
        "motivos_reprovacao": [MOTIVO_REPROVADO_POR_PESO],
    },
    {
        "id": 52,
        "peso": 90,
        "cor": "AZUL",
        "comprimento": 15,
        "status": STATUS_REPROVADO,
        "motivos_reprovacao": [MOTIVO_REPROVADO_POR_PESO],
    },
    {
        "id": 53,
        "peso": 90,
        "cor": "VERDE",
        "comprimento": 15,
        "status": STATUS_REPROVADO,
        "motivos_reprovacao": [MOTIVO_REPROVADO_POR_PESO],
    },
    # Cor inválida
    {
        "id": 54,
        "peso": 100,
        "cor": "VERMELHO",
        "comprimento": 15,
        "status": STATUS_REPROVADO,
        "motivos_reprovacao": [MOTIVO_REPROVADO_POR_COR],
    },
    {
        "id": 55,
        "peso": 100,
        "cor": "PRETO",
        "comprimento": 15,
        "status": STATUS_REPROVADO,
        "motivos_reprovacao": [MOTIVO_REPROVADO_POR_COR],
    },
    {
        "id": 56,
        "peso": 100,
        "cor": "BRANCO",
        "comprimento": 15,
        "status": STATUS_REPROVADO,
        "motivos_reprovacao": [MOTIVO_REPROVADO_POR_COR],
    },
    {
        "id": 57,
        "peso": 100,
        "cor": "AMARELO",
        "comprimento": 15,
        "status": STATUS_REPROVADO,
        "motivos_reprovacao": [MOTIVO_REPROVADO_POR_COR],
    },
    {
        "id": 58,
        "peso": 100,
        "cor": "ROXO",
        "comprimento": 15,
        "status": STATUS_REPROVADO,
        "motivos_reprovacao": [MOTIVO_REPROVADO_POR_COR],
    },
    {
        "id": 59,
        "peso": 100,
        "cor": "LARANJA",
        "comprimento": 15,
        "status": STATUS_REPROVADO,
        "motivos_reprovacao": [MOTIVO_REPROVADO_POR_COR],
    },
    {
        "id": 60,
        "peso": 100,
        "cor": "ROSA",
        "comprimento": 15,
        "status": STATUS_REPROVADO,
        "motivos_reprovacao": [MOTIVO_REPROVADO_POR_COR],
    },
    {
        "id": 61,
        "peso": 100,
        "cor": "CINZA",
        "comprimento": 15,
        "status": STATUS_REPROVADO,
        "motivos_reprovacao": [MOTIVO_REPROVADO_POR_COR],
    },
    {
        "id": 62,
        "peso": 100,
        "cor": "MARROM",
        "comprimento": 15,
        "status": STATUS_REPROVADO,
        "motivos_reprovacao": [MOTIVO_REPROVADO_POR_COR],
    },
    {
        "id": 63,
        "peso": 100,
        "cor": "ROXO",
        "comprimento": 15,
        "status": STATUS_REPROVADO,
        "motivos_reprovacao": [MOTIVO_REPROVADO_POR_COR],
    },
    # Comprimento inválido
    {
        "id": 64,
        "peso": 100,
        "cor": "AZUL",
        "comprimento": 5,
        "status": STATUS_REPROVADO,
        "motivos_reprovacao": [MOTIVO_REPROVADO_POR_COMPRIMENTO],
    },
    {
        "id": 65,
        "peso": 100,
        "cor": "VERDE",
        "comprimento": 5,
        "status": STATUS_REPROVADO,
        "motivos_reprovacao": [MOTIVO_REPROVADO_POR_COMPRIMENTO],
    },
    {
        "id": 66,
        "peso": 100,
        "cor": "AZUL",
        "comprimento": 25,
        "status": STATUS_REPROVADO,
        "motivos_reprovacao": [MOTIVO_REPROVADO_POR_COMPRIMENTO],
    },
    {
        "id": 67,
        "peso": 100,
        "cor": "VERDE",
        "comprimento": 25,
        "status": STATUS_REPROVADO,
        "motivos_reprovacao": [MOTIVO_REPROVADO_POR_COMPRIMENTO],
    },
    {
        "id": 68,
        "peso": 100,
        "cor": "AZUL",
        "comprimento": 30,
        "status": STATUS_REPROVADO,
        "motivos_reprovacao": [MOTIVO_REPROVADO_POR_COMPRIMENTO],
    },
    {
        "id": 69,
        "peso": 100,
        "cor": "VERDE",
        "comprimento": 30,
        "status": STATUS_REPROVADO,
        "motivos_reprovacao": [MOTIVO_REPROVADO_POR_COMPRIMENTO],
    },
    {
        "id": 70,
        "peso": 100,
        "cor": "AZUL",
        "comprimento": 2,
        "status": STATUS_REPROVADO,
        "motivos_reprovacao": [MOTIVO_REPROVADO_POR_COMPRIMENTO],
    },
    {
        "id": 71,
        "peso": 100,
        "cor": "VERDE",
        "comprimento": 2,
        "status": STATUS_REPROVADO,
        "motivos_reprovacao": [MOTIVO_REPROVADO_POR_COMPRIMENTO],
    },
    {
        "id": 72,
        "peso": 100,
        "cor": "AZUL",
        "comprimento": 50,
        "status": STATUS_REPROVADO,
        "motivos_reprovacao": [MOTIVO_REPROVADO_POR_COMPRIMENTO],
    },
    {
        "id": 73,
        "peso": 100,
        "cor": "VERDE",
        "comprimento": 50,
        "status": STATUS_REPROVADO,
        "motivos_reprovacao": [MOTIVO_REPROVADO_POR_COMPRIMENTO],
    },
    # Múltiplos erros
    {
        "id": 74,
        "peso": 50,
        "cor": "ROXO",
        "comprimento": 30,
        "status": STATUS_REPROVADO,
        "motivos_reprovacao": [
            MOTIVO_REPROVADO_POR_PESO,
            MOTIVO_REPROVADO_POR_COR,
            MOTIVO_REPROVADO_POR_COMPRIMENTO,
        ],
    },
    {
        "id": 75,
        "peso": 120,
        "cor": "PRETO",
        "comprimento": 5,
        "status": STATUS_REPROVADO,
        "motivos_reprovacao": [
            MOTIVO_REPROVADO_POR_PESO,
            MOTIVO_REPROVADO_POR_COR,
            MOTIVO_REPROVADO_POR_COMPRIMENTO,
        ],
    },
    {
        "id": 76,
        "peso": 80,
        "cor": "BRANCO",
        "comprimento": 25,
        "status": STATUS_REPROVADO,
        "motivos_reprovacao": [
            MOTIVO_REPROVADO_POR_PESO,
            MOTIVO_REPROVADO_POR_COR,
            MOTIVO_REPROVADO_POR_COMPRIMENTO,
        ],
    },
    {
        "id": 77,
        "peso": 130,
        "cor": "AMARELO",
        "comprimento": 1,
        "status": STATUS_REPROVADO,
        "motivos_reprovacao": [
            MOTIVO_REPROVADO_POR_PESO,
            MOTIVO_REPROVADO_POR_COR,
            MOTIVO_REPROVADO_POR_COMPRIMENTO,
        ],
    },
    {
        "id": 78,
        "peso": 60,
        "cor": "ROSA",
        "comprimento": 40,
        "status": STATUS_REPROVADO,
        "motivos_reprovacao": [
            MOTIVO_REPROVADO_POR_PESO,
            MOTIVO_REPROVADO_POR_COR,
            MOTIVO_REPROVADO_POR_COMPRIMENTO,
        ],
    },
]


def main() -> None:
    pass


def pegar_lista_pecas() -> list[dict]:
    global lista_de_pecas

    return lista_de_pecas


if __name__ == "__main__":
    main()
