### Constantes Controller
LIMITE_ITENS_POR_PAGINA = 20

### Constantes Peças
STATUS_APROVADO = "APROVADO"
STATUS_REPROVADO = "REPROVADO"

MOTIVO_REPROVADO_POR_PESO = "PESO DA PEÇA NÃO SEGUE OS PADRÕES DE QUALIDADE."
MOTIVO_REPROVADO_POR_COR = "COR DA PEÇA NÃO SEGUE OS PADRÕES DE QUALIDADE."
MOTIVO_REPROVADO_POR_COMPRIMENTO = (
    "COMPRIMENTO DA PEÇA NÃO SEGUE OS PADRÕES DE QUALIDADE."
)


def main() -> None:
    pass

if __name__ == "__main__":
    main()